package modele.metier;
// Generated 19 fevr. 2014 17:18:57 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Etat generated by hbm2java
 */
public class Etat  implements java.io.Serializable {


     private int id;
     private String nom;
     private Set commandes = new HashSet(0);

    public Etat() {
    }

	
    public Etat(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }
    public Etat(int id, String nom, Set commandes) {
       this.id = id;
       this.nom = nom;
       this.commandes = commandes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Set commandes) {
        this.commandes = commandes;
    }




}


