package modele.metier;



import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit  implements java.io.Serializable {


     private Integer id;
     private Type type;
     private String nom;
     private int prix;
     private String image;
     private String description;
     private boolean avecEnchere;
     private int quantiteInitiale;
     private Integer quantiteFinale;
     private boolean typeVente;
     private Set produitHasUsers = new HashSet(0);
     private Set encheres = new HashSet(0);
     private Set commandeHasProduits = new HashSet(0);

    public Produit() {
    }

	
    public Produit(Type type, int prix, String image, String description, boolean avecEnchere, int quantiteInitiale, boolean typeVente) {
        this.type = type;
        this.prix = prix;
        this.image = image;
        this.description = description;
        this.avecEnchere = avecEnchere;
        this.quantiteInitiale = quantiteInitiale;
        this.typeVente = typeVente;
    }
    public Produit(Type type, String nom, int prix, String image, String description, boolean avecEnchere, int quantiteInitiale, Integer quantiteFinale, boolean typeVente, Set produitHasUsers, Set encheres, Set commandeHasProduits) {
       this.type = type;
       this.nom = nom;
       this.prix = prix;
       this.image = image;
       this.description = description;
       this.avecEnchere = avecEnchere;
       this.quantiteInitiale = quantiteInitiale;
       this.quantiteFinale = quantiteFinale;
       this.typeVente = typeVente;
       this.produitHasUsers = produitHasUsers;
       this.encheres = encheres;
       this.commandeHasProduits = commandeHasProduits;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public int getPrix() {
        return this.prix;
    }
    
    public void setPrix(int prix) {
        this.prix = prix;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isAvecEnchere() {
        return this.avecEnchere;
    }
    
    public void setAvecEnchere(boolean avecEnchere) {
        this.avecEnchere = avecEnchere;
    }
    public int getQuantiteInitiale() {
        return this.quantiteInitiale;
    }
    
    public void setQuantiteInitiale(int quantiteInitiale) {
        this.quantiteInitiale = quantiteInitiale;
    }
    public Integer getQuantiteFinale() {
        return this.quantiteFinale;
    }
    
    public void setQuantiteFinale(Integer quantiteFinale) {
        this.quantiteFinale = quantiteFinale;
    }
    public boolean isTypeVente() {
        return this.typeVente;
    }
    
    public void setTypeVente(boolean typeVente) {
        this.typeVente = typeVente;
    }
    public Set getProduitHasUsers() {
        return this.produitHasUsers;
    }
    
    public void setProduitHasUsers(Set produitHasUsers) {
        this.produitHasUsers = produitHasUsers;
    }
    public Set getEncheres() {
        return this.encheres;
    }
    
    public void setEncheres(Set encheres) {
        this.encheres = encheres;
    }
    public Set getCommandeHasProduits() {
        return this.commandeHasProduits;
    }
    
    public void setCommandeHasProduits(Set commandeHasProduits) {
        this.commandeHasProduits = commandeHasProduits;
    }




}


