package modele.metier;
// Generated 19 fevr. 2014 17:18:57 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit  implements java.io.Serializable {


     private Integer id;
     private Type type;
     private String nom;
     private String prix;
     private String image;
     private String description;
     private Set produitHasUsers = new HashSet(0);
     private Set commandeHasProduits = new HashSet(0);
     private Set encheres = new HashSet(0);

    public Produit() {
    }

	
    public Produit(Type type, String prix, String image, String description) {
        this.type = type;
        this.prix = prix;
        this.image = image;
        this.description = description;
    }
    public Produit(Type type, String nom, String prix, String image, String description, Set produitHasUsers, Set commandeHasProduits, Set encheres) {
       this.type = type;
       this.nom = nom;
       this.prix = prix;
       this.image = image;
       this.description = description;
       this.produitHasUsers = produitHasUsers;
       this.commandeHasProduits = commandeHasProduits;
       this.encheres = encheres;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrix() {
        return this.prix;
    }
    
    public void setPrix(String prix) {
        this.prix = prix;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getProduitHasUsers() {
        return this.produitHasUsers;
    }
    
    public void setProduitHasUsers(Set produitHasUsers) {
        this.produitHasUsers = produitHasUsers;
    }
    public Set getCommandeHasProduits() {
        return this.commandeHasProduits;
    }
    
    public void setCommandeHasProduits(Set commandeHasProduits) {
        this.commandeHasProduits = commandeHasProduits;
    }
    public Set getEncheres() {
        return this.encheres;
    }
    
    public void setEncheres(Set encheres) {
        this.encheres = encheres;
    }




}


