package modele.metier;



import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String categorie;
     private Set saisons = new HashSet(0);
     private Set produits = new HashSet(0);

    public Type() {
    }

	
    public Type(String nom, String categorie) {
        this.nom = nom;
        this.categorie = categorie;
    }
    public Type(String nom, String categorie, Set saisons, Set produits) {
       this.nom = nom;
       this.categorie = categorie;
       this.saisons = saisons;
       this.produits = produits;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }
    public Set getSaisons() {
        return this.saisons;
    }
    
    public void setSaisons(Set saisons) {
        this.saisons = saisons;
    }
    public Set getProduits() {
        return this.produits;
    }
    
    public void setProduits(Set produits) {
        this.produits = produits;
    }




}


