package modele.metier;


import java.util.Date;

/**
 * Enchere generated by hbm2java
 */
public class Enchere  implements java.io.Serializable {


     private Integer id;
     private Produit produit;
     private Date dateDebut;
     private float prix;
     private Integer intUserId;
     private Date dateFin;

    public Enchere() {
    }

	
    public Enchere(Produit produit, Date dateDebut, float prix, Date dateFin) {
        this.produit = produit;
        this.dateDebut = dateDebut;
        this.prix = prix;
        this.dateFin = dateFin;
    }
    public Enchere(Produit produit, Date dateDebut, float prix, Integer intUserId, Date dateFin) {
       this.produit = produit;
       this.dateDebut = dateDebut;
       this.prix = prix;
       this.intUserId = intUserId;
       this.dateFin = dateFin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public float getPrix() {
        return this.prix;
    }
    
    public void setPrix(float prix) {
        this.prix = prix;
    }
    public Integer getIntUserId() {
        return this.intUserId;
    }
    
    public void setIntUserId(Integer intUserId) {
        this.intUserId = intUserId;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }




}


