package modele.metier;




/**
 * ProduitHasUser generated by hbm2java
 */
public class ProduitHasUser  implements java.io.Serializable {


     private Integer id;
     private Produit produit;
     private User user;
     private int quantiteInit;
     private int quantite;

    public ProduitHasUser() {
    }

    public ProduitHasUser(Produit produit, User user, int quantiteInit, int quantite) {
       this.produit = produit;
       this.user = user;
       this.quantiteInit = quantiteInit;
       this.quantite = quantite;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getQuantiteInit() {
        return this.quantiteInit;
    }
    
    public void setQuantiteInit(int quantiteInit) {
        this.quantiteInit = quantiteInit;
    }
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }




}


