package modele.metier;



import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit  implements java.io.Serializable {


     private Integer id;
     private Type type;
     private User user;
     private String nom;
     private int prix;
     private String image;
     private String description;
     private boolean avecEnchere;
     private Boolean typeVente;
     private int quantiteInitiale;
     private int quantiteFinale;
     private Set encheres = new HashSet(0);
     private Set commandeHasProduits = new HashSet(0);

    public Produit() {
    }

	
    public Produit(Type type, User user, int prix, String image, String description, boolean avecEnchere, int quantiteInitiale, int quantiteFinale) {
        this.type = type;
        this.user = user;
        this.prix = prix;
        this.image = image;
        this.description = description;
        this.avecEnchere = avecEnchere;
        this.quantiteInitiale = quantiteInitiale;
        this.quantiteFinale = quantiteFinale;
    }
    public Produit(Type type, User user, String nom, int prix, String image, String description, boolean avecEnchere, Boolean typeVente, int quantiteInitiale, int quantiteFinale, Set encheres, Set commandeHasProduits) {
       this.type = type;
       this.user = user;
       this.nom = nom;
       this.prix = prix;
       this.image = image;
       this.description = description;
       this.avecEnchere = avecEnchere;
       this.typeVente = typeVente;
       this.quantiteInitiale = quantiteInitiale;
       this.quantiteFinale = quantiteFinale;
       this.encheres = encheres;
       this.commandeHasProduits = commandeHasProduits;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public int getPrix() {
        return this.prix;
    }
    
    public void setPrix(int prix) {
        this.prix = prix;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isAvecEnchere() {
        return this.avecEnchere;
    }
    
    public void setAvecEnchere(boolean avecEnchere) {
        this.avecEnchere = avecEnchere;
    }
    public Boolean getTypeVente() {
        return this.typeVente;
    }
    
    public void setTypeVente(Boolean typeVente) {
        this.typeVente = typeVente;
    }
    public int getQuantiteInitiale() {
        return this.quantiteInitiale;
    }
    
    public void setQuantiteInitiale(int quantiteInitiale) {
        this.quantiteInitiale = quantiteInitiale;
    }
    public int getQuantiteFinale() {
        return this.quantiteFinale;
    }
    
    public void setQuantiteFinale(int quantiteFinale) {
        this.quantiteFinale = quantiteFinale;
    }
    public Set getEncheres() {
        return this.encheres;
    }
    
    public void setEncheres(Set encheres) {
        this.encheres = encheres;
    }
    public Set getCommandeHasProduits() {
        return this.commandeHasProduits;
    }
    
    public void setCommandeHasProduits(Set commandeHasProduits) {
        this.commandeHasProduits = commandeHasProduits;
    }

    public List convertirSetEnList(Set set){
        List list = new ArrayList(set);
        return list;
    }


}


