package modele.metier;
// Generated 24 fevr. 2014 10:17:38 by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Saison generated by hbm2java
 */
public class Saison  implements java.io.Serializable {


     private String nom;
     private Set types = new HashSet(0);

    public Saison() {
    }

	
    public Saison(String nom) {
        this.nom = nom;
    }
    public Saison(String nom, Set types) {
       this.nom = nom;
       this.types = types;
    }
   
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getTypes() {
        return this.types;
    }
    
    public void setTypes(Set types) {
        this.types = types;
    }

   public List convertirSetEnList(Set set){
        List list = new ArrayList(set);
        return list;
    }


}


