package modele.metier;
// Generated 22 fevr. 2014 10:53:47 by Hibernate Tools 3.6.0



import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private Set saisons = new HashSet(0);
     private Set produits = new HashSet(0);

    public Type() {
    }

	
    public Type(String nom) {
        this.nom = nom;
    }
    public Type(String nom, Set saisons, Set produits) {
       this.nom = nom;
       this.saisons = saisons;
       this.produits = produits;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getSaisons() {
        return this.saisons;
    }
    
    public void setSaisons(Set saisons) {
        this.saisons = saisons;
    }
    public Set getProduits() {
        return this.produits;
    }
    
    public void setProduits(Set produits) {
        this.produits = produits;
    }




}


